
version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore: "
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
      time: "12:05"
      timezone: "America/Chicago"
    allow:
      - dependency-name: "@carbon/icons"
      - dependency-name: "@carbon/icons-react"
