name: Optimize SVGs
on:
  pull_request:
    paths:
      - "**.svg"

jobs:
  build:
    name: Process SVGs
    runs-on: ubuntu-latest
    steps:
    - uses: ericcornelissen/svgo-action@v1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        svgo-options: .github/svgo-options.yml
        comment: true
        commit:
          title: "chore: process svgs"
          body: performed by SVGO GitHub Action