name: SVG Processing
on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: svgo-action
      uses: ericcornelissen/svgo-action@v1.3.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
